Every single classification has its own biases and does not enjou superiory over thers

In [1]:
import scipy as sp
import numpy as np
import pandas as pd
from sympy import *

Thus, Rosenblatt's initial perceptron rule is fairly simple and can be summarized by the following steps:
1. Initialize the weights to 0 or small random numbers.
2. For each training sample x(i) perform the following steps:
 1. Compute the output value yˆ .
 2. Update the weights.

In [26]:
np.random.seed(12)
X = np.random.randn(4,5)
y = [1,1,-1,1]
eta=0.01
n_iter=10
w = np.zeros(1 + X.shape[1])
errors = []

In [39]:
out = np.dot(X, w[1:]) + w[0]
errors = out-y
eta * np.dot(X.T, errors)

array([ 0.00586062,  0.0013624 ,  0.01887613,  0.02322079, -0.03492402])

In [24]:
for xi, target in zip(X, y):
    print(xi)
    print(target)

[  6.84901851e-01  -4.58404648e-01   1.54986851e-04  -5.27570534e-01
   1.22673047e-01]
1
[ 0.62169884 -0.36192734 -0.21895215 -1.64008967 -0.69497986]
1
[ 0.60717296 -0.36905758  0.97832874 -1.15407406  0.16456298]
-1
[-0.29156577 -0.00612563 -1.81164727 -0.53339836  0.99452069]
1


### Adaline

In the adaline function instead of unit step function we use a linear function. The advantage of using linear function is that it is a convex function and can be minimized to a local minima. 

- The concept of gradient descent is that a local minima can be achieved until a global cost function

- We take a step away from the gradient in each interation and the step size is determined by the value of learning rate as well as the slope of gradient


As this is run on the entire training data it is called as batch tarining algorithm. When the data is in millions this becomes computationally inefficient and henc ewe use stichastic gradient descent

### Stochastic Gradient Descent

In this instead of updating teh weights based on the accumulated errors of all samples we update the weight incrementally for each sample. 

- Although stochastic gradient descent can be considered as an approximation of gradient descent, it typically reaches convergence much faster because of the more frequent weight updates

- stochastic gradient descent can escape shallow local minima more readily. To obtain accurate results via stochastic gradient descent, it is important to present it with data in a random order

> In stochastic gradient descent implementations, the fixed learning rate η is often replaced by an adaptive learning rate that decreases over time

- stochastic gradient descent does not reach the global minimum but an area very close to it. By using an adaptive learning rate, we can achieve further annealing to a better global minimum


"No Free Lunch" theorem: no single classifier works best across all possible scenarios. In practice, it is always recommended that you compare the performance of at least a handful of different learning algorithms to select the best model for the particular problem; these may differ in the number of features
or samples, the amount of noise in a dataset, and whether the classes are linearly separable or not.